### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by Aquib001** [EggUncle/XposedNavigationBar#1]
Please Translate the App to use Full English language even for options inside cases too.
Also add Clipboard Copy paste option for the Navbar.

**Comment by EggUncle** [comment]
thanks for your suggesstion，I translate it full，at your first time launch this app and change language，maybe need restart this app，and then it will full translate，this a small bug.   :  )




获取 Outlook for Android







On Mon, Jun 19, 2017 at 3:21 AM +0800, "Aquib001" <notifications@github.com> wrote:












Please Translate the App to use Full English language even for options inside cases too.

Also add Clipboard Copy paste option for the Navbar.
