### ISSUE TITLE
The notificanions down button.

### ISSUE THREAD

**Issue by utmuk** [EggUncle/XposedNavigationBar#10]
When I press "drop-down notification" button on XposedNavigationBar, notifications open and when I press it again the notifications close. But if I press the button and then close notification by hand or by pressing on one of notifications, XposedNavigationBar thinks they are open and the next press will do nothing. Can you please make it so that the notifications button always "opens" notifications and not closes. When they are open it is always easy to close them by hand.

**Comment by EggUncle** [comment]
that's sound a good suggestion , I will make it.
thank you :  )
