### ISSUE TITLE
Navbar height

### ISSUE THREAD

**Issue by Mitezuss** [EggUncle/XposedNavigationBar#12]
Change but back to normal size when i go to home... 

Nougat 7.1.2

**Comment by EggUncle** [comment]
i will fix it.....I am too busy to forget this,sorry.

**Comment by Mitezuss** [comment]
Ok =)

I'm trying to use "Dimensions Editor" (xposed module), but maybe there are problem with compatibility because do not work.

**Comment by Afsar-Pasha** [comment]
@EggUncle I suggest you to add a option to disable changing the navigation bar height gravitybox works fine with this module, It conflicts with gravitybox so i'm currently using the same size in both the modules.
