### ISSUE TITLE
Option to Overscale Icons

### ISSUE THREAD

**Issue by Afsar-Pasha** [EggUncle/XposedNavigationBar#2]
Can you add option to **overscale icons**. I use gravity box to reduce navigation bar height, navigation bar icon looks fine but the module's icon are small even if icon size set to 100%.

**Comment by EggUncle** [comment]
ok,I will add this function on next version , thanks for your suggession  :  )

**Comment by Afsar-Pasha** [comment]
Not working on 2.0.1-beta

**Comment by EggUncle** [comment]
please try to uninstall this,then install it.(not just reinstall, maybe need clear this's data)

**Comment by EggUncle** [comment]
on the other hand , how about your 'not working'? couldn't open this app?or you can open this ,and see the small point on main NavBar ,but click it without any response?

**Comment by Afsar-Pasha** [comment]
App works fine, but the option "adjust the icon size" not working, changing the value doesn't work. The icon stays to default size, I can't increase or decrease the icon size.

**Comment by EggUncle** [comment]
maybe icon size not enought big ,  I will try to improve the limit of icon size.

**Comment by Afsar-Pasha** [comment]
On 3.0.1-beta "adjust the icon size" option works good but I have to set it to 18% to make the icon size to adjust the size of my navbar icon if the icon size is set to 100% I can only see some white blocks, anyway that's not the problem the music controller icon is still small.

**Comment by EggUncle** [comment]
Maybe icon is too bigger so make you only see some white blocks , try to adjust smaller.
About the music controller , you are right...I will fix it.

by the way , the lastest xpnavbar's version is 2.0.3-beta   : p
thanks for your suggesstion about this during these days , I will make it better  :  )

**Comment by Afsar-Pasha** [comment]
Make the same to back icon when adjusting brightness and volume.

**Comment by Afsar-Pasha** [comment]
Music controller icon size fixed on v2.0.4. Still waiting for size of back icon when adjusting luminance and volume.
