### ISSUE TITLE
Custom shortcut on swipe to right

### ISSUE THREAD

**Issue by Afsar-Pasha** [EggUncle/XposedNavigationBar#3]
Can you add option set custom shortcut when swiping to right.

**Comment by EggUncle** [comment]
what's your meaning....custom the small point on main NavBar?or custom the shortcut icon?
you can click the short item on setting page,then you can custom the shortcut icon.

**Comment by Afsar-Pasha** [comment]
I meant the music controller.

**Comment by EggUncle** [comment]
ok I will make it.
