### ISSUE TITLE
Icons size & suggestions

### ISSUE THREAD

**Issue by ai94iq** [EggUncle/XposedNavigationBar#6]
Hi buddy

The stock icons doesn't get as big as the other icons, stock icons i mean (back, recent & home). Check screens
https://s2.postimg.org/ki3apv909/Pics_Art_08-27-08.02.00.png

https://s2.postimg.org/45t904uop/Pics_Art_08-27-08.02.17.png

And can you please add option to set Navbar height ?, It would be really neat to have, another suggestion is can you please add option to set custom actions ?, Like long press for back, or double tap or long press for any button

Check DUI you might get an idea about it
https://github.com/DirtyUnicorns/android_packages_apps_DUI

And please make active button area like stock navbar, all around the buttons, not only if you press the actual button, see that screen
 https://s2.postimg.org/tichnsuhl/20170827_201053.png
The active button is only the actual button icon, its a bit different and easier to press on stock, check this pic
https://s2.postimg.org/6989ljjvd/20170827_201406.png
I pressed all the way on the right side, but it pressed the icon anyways

Thanks for your work, ill try to donate when i get the chance :D

**Comment by EggUncle** [comment]
en..this seem to small,maybe this icon to small, I will try to find more suitable icon img.
about the navbar height , maybe it need more time , I try to hide navbar by change this height to zero , but it not stable, I still try to find a better way.
I used to use DUI in my Nexus5x,there are many interseting function on navbar, like fling navbar.

In fact ,you can custom icon img or icon function, click item on setting page,you can change icon img,and add function  ' command ', you can custom a command to run , if you learn about 'android shell',the function would be useful.

I will  make it better , there are many interesting function , I just need more time.   
thanks.   :  )
